comment:
  layout: header, changes, diff, sunburst
coverage:
  ignore:
  - test
  - doc
  - app
  status:
    patch:
      default:
        target: 40%
    project:
      default:
        target: 40%
