get_data_file_dir – radbelt
get_data_file_dir Function
9 statements
Source File
private function get_data_file_dir(me) result(dir)
Get the directory containing the data files.
Type Bound
shellig_type
Arguments
Type Intent Optional Attributes Name
class(shellig_type), intent(in) :: me
Return Value character(len=:), allocatable
Called by
Source Code
   function get_data_file_dir(me) result(dir)
      class(shellig_type),intent(in) :: me
      character(len=:),allocatable :: dir
      if (allocated(me%igrf_dir)) then
         dir = trim(me%igrf_dir) // '/'
      else
         dir = 'data/igrf/' ! default
      end if
   end function get_data_file_dir
Call graph
feldcof calls get_data_file_dir
igrf calls feldcof
igrfc calls feldcof
get_flux_c_ calls igrfc
get_flux_g_ calls igrf
get_flux_c calls get_flux
get_flux_g calls get_flux
get_flux calls get_flux_c, get_flux_g