get_flux_g – radbelt
get_flux_g Function
11 statements
Source File
public function get_flux_g(lon, lat, height, year, e, imname) result(flux)
Calculate the flux of trapped particles at a specific location and time. This is just a function version of the class method from radbelt_type.
Note
This routine is not efficient at all since it will reload all the files every time it is called.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: lon
geodetic longitude in degrees (east)
real(kind=wp), intent(in) :: lat
geodetic latitude in degrees (north)
real(kind=wp), intent(in) :: height
altitude in km above sea level
real(kind=wp), intent(in) :: year
decimal year for which geomagnetic field is to be calculated (e.g.:1995.5 for day 185 of 1995)
real(kind=wp), intent(in) :: e
minimum energy
integer, intent(in) :: imname
which method to use:
1 -- particle species: electrons, solar activity: min
2 -- particle species: electrons, solar activity: max
3 -- particle species: protons, solar activity: min
4 -- particle species: protons, solar activity: max
Return Value real(kind=wp)
The flux of particles above the given energy, in units of cm^-2 s^-1.
Calls
Called by
Source Code
   function get_flux_g(lon,lat,height,year,e,imname) result(flux)
      real(wp),intent(in) :: lon !! geodetic longitude in degrees (east)
      real(wp),intent(in) :: lat !! geodetic latitude in degrees (north)
      real(wp),intent(in) :: height !! altitude in km above sea level
      real(wp),intent(in) :: year !! decimal year for which geomagnetic field is to
                                  !! be calculated (e.g.:1995.5 for day 185 of 1995)
      real(wp),intent(in) :: e !! minimum energy
      integer,intent(in) :: imname !! which method to use:
                                   !!
                                   !! * 1 -- particle species: electrons, solar activity: min
                                   !! * 2 -- particle species: electrons, solar activity: max
                                   !! * 3 -- particle species: protons, solar activity: min
                                   !! * 4 -- particle species: protons, solar activity: max
      real(wp) :: flux !! The flux of particles above the given energy, in units of cm^-2 s^-1.
      type(radbelt_type) :: radbelt
      flux = radbelt%get_flux(lon,lat,height,year,e,imname)
   end function get_flux_g
Call graph
get_flux_g calls get_flux
get_flux_c_ calls aep8, igrfc
get_flux_g_ calls aep8, igrf
aep8 calls get_data_file_dir, trara1
igrf calls feldcof, feldg, findb0, shellg
igrfc calls feldc, feldcof, findb0, shellc
feldcof calls extrashc, get_data_file_dir, getshc, intershc
findb0 calls stoer
shellc calls shellg
shellg calls geo_to_cart, stoer
trara1 calls trara2
stoer calls feldi
get_flux calls get_flux_g