get_data_file_dir – radbelt
get_data_file_dir Function
9 statements
Source File
private function get_data_file_dir(me) result(dir)
Get the directory containing the data files.
Type Bound
trm_type
Arguments
Type Intent Optional Attributes Name
class(trm_type), intent(in) :: me
Return Value character(len=:), allocatable
Called by
Source Code
   function get_data_file_dir(me) result(dir)
      class(trm_type),intent(in) :: me
      character(len=:),allocatable :: dir
      if (allocated(me%aep8_dir)) then
         dir = trim(me%aep8_dir) // '/'
      else
         dir = 'data/aep8/' ! default
      end if
   end function get_data_file_dir
Call graph
aep8 calls get_data_file_dir
get_flux_c_ calls aep8
get_flux_g_ calls aep8
get_flux_c calls get_flux
get_flux_g calls get_flux
get_flux calls get_flux_c, get_flux_g