get_flux_c_ – radbelt
get_flux_c_ Function
12 statements
Source File
public function get_flux_c_(me, v, year, e, imname) result(flux)
Calculate the flux of trapped particles at a specific location and time. This is an alternate version of get_flux_g_ for cartesian coordinates.
Type Bound
radbelt_type
Arguments
Type Intent Optional Attributes Name
class(radbelt_type), intent(inout) :: me
real(kind=wp), intent(in), dimension(3) :: v
real(kind=wp), intent(in) :: year
decimal year for which geomagnetic field is to be calculated (e.g.:1995.5 for day 185 of 1995)
real(kind=wp), intent(in) :: e
minimum energy
integer, intent(in) :: imname
which method to use:
1 -- particle species: electrons, solar activity: min
2 -- particle species: electrons, solar activity: max
3 -- particle species: protons, solar activity: min
4 -- particle species: protons, solar activity: max
Return Value real(kind=wp)
The flux of particles above the given energy, in units of cm^-2 s^-1.
Calls
Called by
Source Code
   function get_flux_c_(me,v,year,e,imname) result(flux)
      class(radbelt_type),intent(inout) :: me
      real(wp),dimension(3),intent(in) :: v
      real(wp),intent(in) :: year !! decimal year for which geomagnetic field is to
                                  !! be calculated (e.g.:1995.5 for day 185 of 1995)
      real(wp),intent(in) :: e !! minimum energy
      integer,intent(in) :: imname !! which method to use:
                                   !!
                                   !! * 1 -- particle species: electrons, solar activity: min
                                   !! * 2 -- particle species: electrons, solar activity: max
                                   !! * 3 -- particle species: protons, solar activity: min
                                   !! * 4 -- particle species: protons, solar activity: max
      real(wp) :: flux !! The flux of particles above the given energy, in units of cm^-2 s^-1.
      real(wp) :: xl !! l value
      real(wp) :: bbx
      call me%igrf%igrfc(v,year,xl,bbx)
      call me%trm%aep8(e,xl,bbx,imname,flux)
   end function get_flux_c_
Call graph
get_flux_c_ calls aep8, igrfc
aep8 calls get_data_file_dir, trara1
igrfc calls feldc, feldcof, findb0, shellc
feldcof calls extrashc, get_data_file_dir, getshc, intershc
findb0 calls stoer
shellc calls shellg
trara1 calls trara2
shellg calls stoer, geo_to_cart
stoer calls feldi
get_flux_c calls get_flux
get_flux_g calls get_flux
get_flux_g_c calls get_flux
get_flux calls get_flux_c, get_flux_g