get_flux_ – radbelt
get_flux_ Function
14 statements
Source File
public function get_flux_(me, lon, lat, height, year, e, imname) result(flux)
Calculate the flux of trapped particles at a specific location and time.
Type Bound
radbelt_type
Arguments
Type Intent Optional Attributes Name
class(radbelt_type), intent(inout) :: me
real(kind=wp), intent(in) :: lon
geodetic longitude in degrees (east)
real(kind=wp), intent(in) :: lat
geodetic latitude in degrees (north)
real(kind=wp), intent(in) :: height
altitude in km above sea level
real(kind=wp), intent(in) :: year
decimal year for which geomagnetic field is to be calculated (e.g.:1995.5 for day 185 of 1995)
real(kind=wp), intent(in) :: e
minimum energy
integer, intent(in) :: imname
which method to use:
1 -- particle species: electrons, solar activity: min
2 -- particle species: electrons, solar activity: max
3 -- particle species: protons, solar activity: min
4 -- particle species: protons, solar activity: max
Return Value real(kind=wp)
The flux of particles above the given energy, in units of cm^-2 s^-1.
Calls
Called by
Source Code
   function get_flux_(me,lon,lat,height,year,e,imname) result(flux)
      class(radbelt_type),intent(inout) :: me
      real(wp),intent(in) :: lon !! geodetic longitude in degrees (east)
      real(wp),intent(in) :: lat !! geodetic latitude in degrees (north)
      real(wp),intent(in) :: height !! altitude in km above sea level
      real(wp),intent(in) :: year !! decimal year for which geomagnetic field is to
                                  !! be calculated (e.g.:1995.5 for day 185 of 1995)
      real(wp),intent(in) :: e !! minimum energy
      integer,intent(in) :: imname !! which method to use:
                                   !!
                                   !! * 1 -- particle species: electrons, solar activity: min
                                   !! * 2 -- particle species: electrons, solar activity: max
                                   !! * 3 -- particle species: protons, solar activity: min
                                   !! * 4 -- particle species: protons, solar activity: max
      real(wp) :: flux !! The flux of particles above the given energy, in units of cm^-2 s^-1.
      real(wp) :: xl !! l value
      real(wp) :: bbx
      call me%igrf%igrf(lon,lat,height,year,xl,bbx)
      call me%trm%aep8(e,xl,bbx,imname,flux)
   end function get_flux_
Call graph
get_flux_ calls aep8, igrf
aep8 calls get_data_file_dir, trara1
igrf calls feldcof, feldg, findb0, shellg
feldcof calls extrashc, get_data_file_dir, getshc, intershc
feldg calls feldc, feldi
findb0 calls stoer
shellg calls stoer, shellc
trara1 calls trara2
stoer calls feldi
get_flux calls get_flux_