getshc – radbelt
getshc Subroutine
40 statements
Source File
private subroutine getshc(me, Fspec, Nmax, Erad, Gh, Ier)
Reads spherical harmonic coefficients from the specified file into an array.
Author
Version 1.01, A. Zunde, USGS, MS 964, Box 25046 Federal Center, Denver, CO 80225
Type Bound
shellig_type
Arguments
Type Intent Optional Attributes Name
class(shellig_type), intent(inout) :: me
character(len=*), intent(in) :: Fspec
File specification
integer, intent(out) :: Nmax
Maximum degree and order of model
real(kind=wp), intent(out) :: Erad
Earth's radius associated with the spherical harmonic coefficients, in the same units as elevation
real(kind=wp), intent(out), dimension(*) :: Gh
Schmidt quasi-normal internal spherical harmonic coefficients
integer, intent(out) :: Ier
Error number:
0, no error
-2, records out of order
FORTRAN run-time error number
Called by
Source Code
subroutine getshc(me,Fspec,Nmax,Erad,Gh,Ier)
   class(shellig_type),intent(inout) :: me
   character(len=*),intent(in) :: Fspec !! File specification
   integer,intent(out) :: Nmax !! Maximum degree and order of model
   real(wp),intent(out) :: Erad !! Earth's radius associated with the spherical
                                !! harmonic coefficients, in the same units as
                                !! elevation
   real(wp),dimension(*),intent(out) :: Gh !! Schmidt quasi-normal internal spherical
                                           !! harmonic coefficients
   integer,intent(out) :: Ier !! Error number:
                              !!
                              !!  * 0, no error
                              !!  * -2, records out of order
                              !!  * FORTRAN run-time error number
   integer :: iu !! logical unit number
   real(wp) :: g , h
   integer :: i , m , mm , n , nn
   read_file : block
      ! ---------------------------------------------------------------
      !  Open coefficient file. Read past first header record.
      !  Read degree and order of model and Earth's radius.
      ! ---------------------------------------------------------------
      OPEN (newunit=Iu,FILE=Fspec,STATUS='OLD',IOSTAT=Ier)
      if (Ier/=0) then
         write(*,*) 'Error opening file: '//trim(fspec)
         exit read_file
      end if
      READ (Iu,*,IOSTAT=Ier)
      if (Ier/=0) exit read_file
      READ (Iu,*,IOSTAT=Ier) Nmax , Erad
      if (Ier/=0) exit read_file
      ! ---------------------------------------------------------------
      !  Read the coefficient file, arranged as follows:
      !
      !          N     M     G     H
      !          ----------------------
      !            /   1     0    GH(1)  -
      !           /  1     1    GH(2) GH(3)
      !          /  2     0    GH(4)  -
      !         /  2     1    GH(5) GH(6)
      !      NMAX*(NMAX+3)/2   /  2     2    GH(7) GH(8)
      !         records    \  3     0    GH(9)  -
      !         \      .     .     .     .
      !          \  .     .     .     .
      !      NMAX*(NMAX+2)     \  .     .     .     .
      !      elements in GH      \  NMAX  NMAX   .     .
      !
      !  N and M are, respectively, the degree and order of the
      !  coefficient.
      ! ---------------------------------------------------------------
      i = 0
      main: DO nn = 1 , Nmax
         DO mm = 0 , nn
            READ (Iu,*,IOSTAT=Ier) n , m , g , h
            if (Ier/=0) exit main
            IF ( nn/=n .OR. mm/=m ) THEN
               Ier = -2
               EXIT main
            ENDIF
            i = i + 1
            Gh(i) = g
            IF ( m/=0 ) THEN
               i = i + 1
               Gh(i) = h
            ENDIF
         ENDDO
      ENDDO main
   end block read_file
   CLOSE (Iu)
END subroutine getshc
Call graph
feldcof calls getshc
igrf calls feldcof
igrfc calls feldcof
get_flux_c_ calls igrfc
get_flux_g_ calls igrf
get_flux_c calls get_flux
get_flux_g calls get_flux
get_flux calls get_flux_c, get_flux_g