intershc – radbelt
intershc Subroutine
36 statements
Source File
private subroutine intershc(me, date, dte1, nmax1, gh1, dte2, nmax2, gh2, nmax, gh)
Interpolates linearly, in time, between two spherical harmonic models.
The coefficients (GH) of the resulting model, at date DATE, are computed by linearly interpolating between the coefficients of the earlier model (GH1), at date DTE1, and those of the later model (GH2), at date DTE2. If one model is smaller than the other, the interpolation is performed with the missing coefficients assumed to be 0.
Author
Version 1.01, A. Zunde USGS, MS 964, Box 25046 Federal Center, Denver, CO 80225
Type Bound
shellig_type
Arguments
Type Intent Optional Attributes Name
class(shellig_type), intent(inout) :: me
real(kind=wp), intent(in) :: date
Date of resulting model (in decimal year)
real(kind=wp), intent(in) :: dte1
Date of earlier model
integer, intent(in) :: nmax1
Maximum degree and order of earlier model
real(kind=wp), intent(in) :: gh1(*)
Schmidt quasi-normal internal spherical harmonic coefficients of earlier model
real(kind=wp), intent(in) :: dte2
Date of later model
integer, intent(in) :: nmax2
Maximum degree and order of later model
real(kind=wp), intent(in) :: gh2(*)
Schmidt quasi-normal internal spherical harmonic coefficients of later model
integer, intent(out) :: nmax
Maximum degree and order of resulting model
real(kind=wp), intent(out) :: gh(*)
Coefficients of resulting model
Called by
Source Code
subroutine intershc(me,date,dte1,nmax1,gh1,dte2,nmax2,gh2,nmax,gh)
   class(shellig_type),intent(inout) :: me
   real(wp),intent(in) :: date !! Date of resulting model (in decimal year)
   real(wp),intent(in) :: dte1 !! Date of earlier model
   integer,intent(in) :: nmax1 !! Maximum degree and order of earlier model
   real(wp),intent(in) :: gh1(*) !! Schmidt quasi-normal internal spherical harmonic coefficients of earlier model
   real(wp),intent(in) :: dte2 !! Date of later model
   integer,intent(in) :: nmax2 !! Maximum degree and order of later model
   real(wp),intent(in) :: gh2(*) !! Schmidt quasi-normal internal spherical harmonic coefficients of later model
   real(wp),intent(out) :: gh(*) !! Coefficients of resulting model
   integer,intent(out) :: nmax !! Maximum degree and order of resulting model
   real(wp) :: factor
   integer :: i , k , l
   factor = (date-dte1)/(dte2-dte1)
   if ( nmax1==nmax2 ) then
      k = nmax1*(nmax1+2)
      nmax = nmax1
   elseif ( nmax1>nmax2 ) then
      k = nmax2*(nmax2+2)
      l = nmax1*(nmax1+2)
      do i = k + 1 , l
         gh(i) = gh1(i) + factor*(-gh1(i))
      enddo
      nmax = nmax1
   else
      k = nmax1*(nmax1+2)
      l = nmax2*(nmax2+2)
      do i = k + 1 , l
         gh(i) = factor*gh2(i)
      enddo
      nmax = nmax2
   endif
   do i = 1 , k
      gh(i) = gh1(i) + factor*(gh2(i)-gh1(i))
   enddo
end subroutine intershc
Call graph
feldcof calls intershc
igrf calls feldcof
igrfc calls feldcof
get_flux_c_ calls igrfc
get_flux_g_ calls igrf
get_flux_c calls get_flux
get_flux_g calls get_flux
get_flux calls get_flux_c, get_flux_g