shellc – radbelt
shellc Subroutine
10 statements
Source File
private subroutine shellc(me, v, dimo, fl, icode, b0)
Wrapper to shellg to be used with cartesian coordinates.
Note
In the original code, this was an ENTRY point in shellg and didn't include all the outputs.
Type Bound
shellig_type
Arguments
Type Intent Optional Attributes Name
class(shellig_type), intent(inout) :: me
real(kind=wp), intent(in), dimension(3) :: v
cartesian coordinates in earth radii (6371.2 km) * x-axis pointing to equator at 0 longitude * y-axis pointing to equator at 90 long. * z-axis pointing to north pole
real(kind=wp), intent(in) :: dimo
dipol moment in gauss (normalized to earth radius)
real(kind=wp), intent(out) :: fl
l-value
integer, intent(out) :: icode
=1 normal completion
=2 unphysical conjugate point (fl meaningless)
=3 shell parameter greater than limit up to which accurate calculation is required; approximation is used.
real(kind=wp), intent(out) :: b0
magnetic field strength in gauss
Calls
Called by
Source Code
  subroutine shellc(me,v,dimo,fl,icode,b0)
   class(shellig_type),intent(inout) :: me
   real(wp),dimension(3),intent(in) :: v !! cartesian coordinates in earth radii (6371.2 km)
                                         !! * x-axis pointing to equator at 0 longitude
                                         !! * y-axis pointing to equator at 90 long.
                                         !! * z-axis pointing to north pole
   real(wp),intent(in) :: dimo !! dipol moment in gauss (normalized to earth radius)
   real(wp),intent(out) :: fl  !! l-value
   integer,intent(out) :: icode  !! * =1 normal completion
                                 !! * =2 unphysical conjugate point (fl meaningless)
                                 !! * =3 shell parameter greater than limit up to
                                 !!   which accurate calculation is required;
                                 !!   approximation is used.
   real(wp),intent(out) :: b0 !! magnetic field strength in gauss
   real(wp) :: glat,glon,alt !! not used
   call me%shellg(glat,glon,alt,dimo,fl,icode,b0,v)
  end subroutine shellc
Call graph
shellc calls shellg
shellg calls geo_to_cart, stoer
stoer calls feldi
igrfc calls shellc
get_flux_c_ calls igrfc
get_flux_c calls get_flux
get_flux_g calls get_flux
get_flux_g_c calls get_flux
get_flux calls get_flux_c, get_flux_g